# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Global Fishing Watch Data
contact: http://globalfishingwatch.org/contact-us
description: > # this means to ignore newlines until "baseurl:"
  Unless otherwise stated, all Global Fishing Watch data and code is is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.
baseurl: "/ju6WuV7r" # the subpath of your site, e.g. /blog
url: "/." # the base hostname & protocol for your site
twitter_username: globalfishwatch
github_username:  globalfishingwatch

# Build settings
markdown: kramdown
theme: minima

include: ['_pages']

authors:
  hanzou:
    name: David Kroodsma
    display_name: David
    gravatar: c66919cb194f96c696c1da0c47354a6a
    email: davidk@skytruth.org
    web: http://globalfishingwatch.org
    twitter: davidkroodsma
    github: davidkroodsma
  jorgen:
    name: Egil Moeller
    display_name: Egil
    gravatar: 12e480a364a5c19214f99b4dfe9a11d5
    email: egil@skytruth.org
    web: http://globalfishingwatch.org
    twitter: redhog
    github: redhog